image: gcc
build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - apt update && apt -y install make cmake
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j
  artifacts:
    paths:
      - build/lib/libmalkt.a
      - build/bin/gtests
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - "build/"
test:
  stage: test
  before_script:
    - apt update && apt -y install gcovr
  script:
    - cd build
    - bin/gtests --gtest_output="xml:../report.xml"
    - gcovr src/CMakeFiles/malkt.dir -r ../src
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - "build/"
    policy: pull
